# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filerecord_zipped_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='filename',
            field=models.CharField(default='qwerty', max_length=100),
            preserve_default=False,
        ),
    ]
